// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7724e210-f50b-4faa-8018-8394af836276",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_GtxDYTwao",
    "aws_user_pools_web_client_id": "1v2ct0ig3bqkt3t27g8nfama7l"
};


export default awsmobile;
